#! /bin/bash -f
# Written by Aaron Kucyi
# compatible with BIDS or BIDS-like organized data

# Required inputs:
# 1. Path to bids dataset folder 
# 2. Subject name

usage() {
	echo ""
	echo "Usage: step1_run_alignment_onesubject <path_to_bids_folder> <subject_name>"
	echo "example: step1_run_alignment_onesubject /work/kucyi/data/Hung_MW/data MW01"
	echo "(2 inputs required)"
	echo "This function creates a common BOLD template by taking mean across all runs and sessions, then it aligns all runs to the template"
	echo "output will be in <path_to_bids_folder>/derivatives/subject/iProc"
}

if [[ $# -eq 0 ]] ; then
	usage
	exit
fi

## Initate inputs, paths and output paths
bids_path=$1
sub=$2
path=`echo ${bids_path%/*}`
data_folder=`basename ${bids_path}`
mkdir -p ${path}/derivatives
mkdir -p ${path}/derivatives/${sub}
mkdir -p ${path}/derivatives/${sub}/iProc
rm -r -f ${path}/derivatives/${sub}/iProc/bold_template
mkdir -p ${path}/derivatives/${sub}/iProc/bold_template

## get sessions
sessions=$(ls -t ${bids_path}/${sub})
echo "sessions are ${sessions}"
## compute mean within each run in each session
for session in $sessions
do
mkdir -p ${path}/derivatives/${sub}/iProc/${session}
mkdir -p ${path}/derivatives/${sub}/iProc/${session}/func
# get nifti files for each run in this session
runs=`find ${path}/${data_folder}/${sub}/${session}/func -name "*nii*"`
echo "runs for ${session} are ${runs}"
# loop through runs
for run in $runs
do
	run=`basename ${run}`
	fslmaths ${path}/${data_folder}/${sub}/${session}/func/${run} -Tmean ${path}/derivatives/${sub}/iProc/bold_template/${session}_${run}_mean
	echo "done computing mean for ${sub} ${session} ${run}"
done
done

## concatenate run means then compute mean of all
all_runs=`find ${path}/derivatives/${sub}/iProc/bold_template -name "*nii*"`
fslmerge -t ${path}/derivatives/${sub}/iProc/bold_template/means_concat ${all_runs}
echo "done merging all runs"
fslmaths ${path}/derivatives/${sub}/iProc/bold_template/means_concat -Tmean ${path}/derivatives/${sub}/iProc/bold_template/mean_bold_template
echo "done computing mean template"

## remove intermediate files
rm -f ${path}/derivatives/${sub}/iProc/bold_template/*mean.nii.gz ${path}/derivatives/${sub}/iProc/bold_template/means_concat.nii.gz

## head motion correction and registration to bold template for each run
for session in $sessions
do
runs=`find ${path}/${data_folder}/${sub}/${session}/func -name "*nii*"`
for run in $runs
do
	run=`basename ${run}`
	# motion correction
	mcflirt -in ${path}/${data_folder}/${sub}/${session}/func/${run} -out ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_mcf -mats -plots -rmsrel -rmsabs -spline_final
	echo "done motion correction for ${sub} ${session} ${run}"
	# register to bold template
	flirt -in ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_mcf -ref ${path}/derivatives/${sub}/iProc/bold_template/mean_bold_template.nii.gz -out ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_template.nii.gz -omat ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_mcf2meanbold.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 12  -interp trilinear
	echo "done registering to bold template"
	# transform to bold template
	flirt -in ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_mcf -ref ${path}/derivatives/${sub}/iProc/bold_template/mean_bold_template.nii.gz -out ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_mcf_template.nii.gz -applyxfm -init ${path}/derivatives/${sub}/iProc/${session}/func/${run%.*}_mcf2meanbold.mat -interp trilinear
	echo "done transforming ${sub} ${session} ${run} to bold template"
done
done


