#! /bin/bash -f

# First, in terminal type "csh"
# Then "source CBIG_preproc_config_aaron.csh"
# Then run this 

usage() {
	echo ""
	echo "run_CBIG_preproc <bids_folder> <subject_name> <session_name> <fmrinii .txt file> <cbig preproc config .txt file> <cbig config .csh file>"
	echo ""
	echo "6 inputs required, and you MUST RUN THIS FROM THE PATH THAT CONTAINS THE LAST 3 INPUT FILES"
	echo "(1) bids path (containing subject folders)"
	echo "(2) subject name"
	echo "(3) session name (if single session, call it ses-001)"
	echo "(4) fmrinii.txt file configured for this dataset (see CBIG repo for examples)"
	echo "(5) .txt file with CBIG preproc parameters specified (see CBIG repo for examples)"
	echo "(6) CBIG config file (.csh) for this system (see CBIG repo for examples)" 
	echo ""
	echo "Example: run_CBIG_preproc ~/Documents/data/R21-rt-fMRI/bids_data sub-001 ses-001 fmrinii.txt mshbm_preproc_config.txt CBIG_preproc_config_aaron.csh"
	echo ""
	echo "Before running this, you must do the following (set up once FOR EACH SYSTEM):"
	echo "(a) Make sure that matlab can be called from the terminal (edit .bashrc or .bash_profile if needed)"
	echo "(b) Copy code from CBIG_preproc_tested_startup.m (from CBIG repo) into Matlab startup.m file"
	echo "(c) Edit your .bashrc or .bash_profile to set path to CBIG_preproc_tools folder pulled to your system"
	echo "(d) set up your CBIG config .csh file with paths specified for all software (see CBIG repo for example)"
	echo ""
	echo "Before running this, you must do the following (set up once FOR EACH PROJECT):"
	echo "(a) manually configure your fmrinii.txt file with paths and all fMRI runs specified for your project/dataset; to do so, specify a ####SUBJECT#### variable and if multi-session data, a ####SESSION#### variable"
	echo ""
	echo "Before running this, you must do the following (set up once FOR EACH SUBJECT):"
	echo "(a) use run_recon function to reconstruct cortical surface with freesurfer"
	echo ""
}

if [[ $# -eq 0 ]] ; then
	usage
	exit
fi

bids_path="$1"
sub="$2"
sess=${3:-1} 
fmrinii=`realpath "$4"`
mshbm_preproc_config=`realpath "$5"`
cbig_config=`realpath "$6"`
 
# set up input/output folders
if [ $sess != 1 ]; then
	sess=ses-01
fi
path=`echo ${bids_path%/*}`
derivs_folder=${path}/derivatives
mkdir -p ${derivs_folder}
mkdir -p ${derivs_folder}/CBIG_preproc
mkdir -p ${derivs_folder}/CBIG_preproc/${sub}
mkdir -p ${derivs_folder}/CBIG_preproc/${sub}/${sess}

# set up fmrinii.txt file (with runs/paths specified)
fmrinii_path=`echo ${fmrinii%/*}`
echo "fmriniipath is ${fmrinii_path}"
cp ${fmrinii} ${fmrinii_path}/fmrinii_${sess}.txt
sed -i " " "s/####SUBJECT####/${sub}/g" "${fmrinii_path}/fmrinii_${sess}.txt"
sed -i " " "s/####SESSION####/${sess}/g" "${fmrinii_path}/fmrinii_${sess}.txt"

# run CBIG preprocessing
#! /bin/tcsh -f
csh -c "source ${cbig_config}; CBIG_preproc_fMRI_preprocess.csh -s ${sub} -fmrinii ${fmrinii_path}/fmrinii_${sess}.txt -anat_s ${sub} -anat_d ${derivs_folder}/freesurfer -output_d ${derivs_folder}/CBIG_preproc/${sub}/${sess} -config ${mshbm_preproc_config}"
rm -f fmrinii_${sess}.txt
echo "done preprocessing for ${sub} ${sess}"

